// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djaqrbetwsanbkwslwfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqYXFyYmV0d3NhbmJrd3Nsd2ZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyOTgwNDksImV4cCI6MjA1NTg3NDA0OX0.4_rCq_qeXzVO2GMBGMVtSR5RhK1nlm6HMii3EmYeC38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);